name: tradingbot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  http: ^1.5.0
  intl: ^0.20.2
  js: ^0.7.2
  path_provider: ^2.1.5
  pointer_interceptor: ^0.10.1+2
  timezone: ^0.10.1
  web: ^1.1.1
  webview_flutter: ^4.13.0
  webview_windows: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
